### PR TITLE
Notebook connection fix

### PR DESCRIPTION
**Pull request by vinodmuralidharan01**
c.NotebookApp.keep_alive = True:

This setting ensures that the connection between the client browser and the Jupyter server remains active. When set to True, it prevents the connection from being dropped during periods of inactivity, allowing us to keep working without interruptions.

c.NotebookApp.connection_timeout = 1800000:

This specifies the time (in milliseconds) the server will wait before timing out a connection. In this case, 30 minutes. If there’s no activity during this period, the server may close the connection.

### CODE REVIEW

**Review by svyotov — COMMENTED** [review]
When I check the logs of the notebook, I am seeing warnings, could you review this please?

**Review by svyotov — DISMISSED** [review]
if tested

**Comment by vinodmuralidharan01** [comment]
c.NotebookApp.shutdown_no_activity_timeout = 3600:

This setting specifies the amount of time (in seconds) that the Jupyter Notebook server will wait for any activity before shutting down the server. In this case, it's set to 3600 seconds, or 60 minutes. If there is no user activity for an hour, the server will automatically shut down.
c.MappingKernelManager.cull_idle_timeout = 3600:

This parameter defines how long (in seconds) an idle kernel can remain running before it is automatically terminated. Here, it is set to 3600 seconds (60 minutes). If a kernel hasn't been used for an hour, it will be culled (terminated) to free up resources.
c.MappingKernelManager.cull_interval = 300:

This setting determines how frequently (in seconds) the Jupyter server checks for idle kernels that can be culled. In this case, it’s set to 300 seconds, or 5 minutes. The server will perform a check every 5 minutes to see if any kernels have been idle long enough to meet the cull_idle_timeout criteria.

**Review by svyotov — APPROVED** [review]
:+1: , LGTM if tested.

**Pull request merged**
